{{- range $name, $service := .Values.services }}
{{- if $service.dbUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-service-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  DATABASE_URL: {{ $service.dbUrl | b64enc }}
  {{- if $service.masterKey }}
  MASTER_KEY: {{ $service.masterKey | b64enc }}
  {{- end }}
---
{{- end }}
{{- if eq $name "evaluation" }}
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  REDIS_URL: {{ $service.redisUrl | b64enc }}
  AWS_SQS_URL: {{ $service.sqsUrl | b64enc }}
  SERVICE_API_KEY: {{ $service.apiKey | b64enc }}
  {{- if $.Values.awsCredentials.accessKey }}
  AWS_ACCESS_KEY_ID: {{ $.Values.awsCredentials.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.awsCredentials.secretKey | b64enc }}
  AWS_SESSION_TOKEN: {{ $.Values.awsCredentials.sessionToken | b64enc }}
  {{- end }}
---
{{- end }}
{{- if eq $name "analytics" }}
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  AWS_SQS_URL: {{ $service.sqsUrl | b64enc }}
  {{- if $.Values.awsCredentials.accessKey }}
  AWS_ACCESS_KEY_ID: {{ $.Values.awsCredentials.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.awsCredentials.secretKey | b64enc }}
  AWS_SESSION_TOKEN: {{ $.Values.awsCredentials.sessionToken | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
