# Global settings
accountID: "123456789012"
region: "us-east-1"

# Common labels
labels:
  project: fiap-toogle

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  host: toogle.example.com

# Services configuration
services:
  auth:
    replicaCount: 1
    image: auth-service
    tag: latest
    port: 8001
    dbUrl: "postgres://dbuser:SenhaTeste123@auth-db-endpoint:5432/auth_db"
    masterKey: "sua_chave_mestra_aqui"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  flag:
    replicaCount: 1
    image: flag-service
    tag: latest
    port: 8002
    dbUrl: "postgres://dbuser:SenhaTeste123@main-db-endpoint:5432/flag_db"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  targeting:
    replicaCount: 1
    image: targeting-service
    tag: latest
    port: 8003
    dbUrl: "postgres://dbuser:SenhaTeste123@targeting-db-endpoint:5432/targeting_db"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  evaluation:
    replicaCount: 2
    image: evaluation-service
    tag: latest
    port: 8004
    redisUrl: "redis://redis-endpoint:6379"
    sqsUrl: "https://sqs.us-east-1.amazonaws.com/123456789012/toogle-events"
    apiKey: "tm_key_f54b81bc161a5b84c277ed954384ae950c87adb8c795892db4abfaef75aaacab"
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPU: 70

  analytics:
    replicaCount: 1
    image: analytics-service
    tag: latest
    port: 8005
    sqsUrl: "https://sqs.us-east-1.amazonaws.com/123456789012/toogle-events"
    dbTable: "analytics_events"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPU: 70

awsCredentials:
  accessKey: ""
  secretKey: ""
  sessionToken: ""
