apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toogle-master
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/oseiasal/fiap_toogle_master_v2.git'
    targetRevision: master
    path: 'k8s/overlays/prod'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: toogle-master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: batch
      kind: Job
      name: ingress-nginx-admission-create
    - group: batch
      kind: Job
      name: ingress-nginx-admission-patch
