apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tooglemaster-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/oseiasal/fiap_toogle_master_v2.git'
    targetRevision: master
    path: 'k8s/argocd/apps'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
