apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/aws/deploy.yaml
  - metrics-server.yaml
  - auth-service.yaml
  - flag-service.yaml
  - targeting-service.yaml
  - evaluation-service.yaml
  - analytics-service.yaml
  - ingress.yaml
