name: DevSecOps Security Scan (IaC & Repository)

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]
  schedule:
    - cron: '0 4 * * 1' # Executa semanalmente toda segunda-feira às 04:00 UTC

concurrency:
  group: security-scan-orchestrator-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: DevSecOps Security Analysis (Trivy FS Scan)
    uses: oseiasal/.github/.github/workflows/reusable-security.yml@main
    with:
      language: 'auto'
      trivy-severity: 'CRITICAL,HIGH'
      fail-on-critical: true
